name             'mycookbook'
maintainer       'Christopher H. Laco'
maintainer_email 'claco@chrislaco.com'
license          'Apache 2.0'
description      'Installs/Configures mycookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apt'
depends          'build-essential'
depends          'database'
depends          'mysql'
depends          'users'
